/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ExecuteMsg =
  | {
      add_new: {
        amount: number;
        id: string;
        name: string;
        price: number;
        [k: string]: unknown;
      };
    }
  | {
      sell: {
        amount: number;
        id: string;
        [k: string]: unknown;
      };
    };
